### ISSUE TITLE
[bitnami/mongodb-sharded] Unrecognized option: storage.journal.enabled when starting mongodb

### ISSUE THREAD

**Issue by muyukha** [bitnami/containers#50109]
### Name and Version

mongodb-sharded-6.6.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I deployed  mongodb on the GKE cluster. It has been running well but yesterday all pods in the statefulset went down with an error Unrecognized option: storage.journal.enabled.

I deployed via helm.
Helm repository https://charts.bitnami.com/bitnami

### What do you see instead?
```
 05:54:06.20 INFO  ==> Setting node as primary
mongodb 05:54:06.23 
mongodb 05:54:06.24 Welcome to the Bitnami mongodb-sharded container
mongodb 05:54:06.24 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 05:54:06.24 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 05:54:06.24 
mongodb 05:54:06.24 INFO  ==> ** Starting MongoDB Sharded setup **
mongodb 05:54:06.27 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 05:54:06.33 INFO  ==> Initializing MongoDB Sharded...
mongodb 05:54:06.37 INFO  ==> Writing keyfile for replica set authentication...
mongodb 05:54:06.39 INFO  ==> Enabling authentication...
mongodb 05:54:06.39 INFO  ==> Deploying MongoDB Sharded with persisted data...

mongodb 05:54:06.43 INFO  ==> ** MongoDB Sharded setup finished! **
mongodb 05:54:06.47 INFO  ==> ** Starting MongoDB **
Unrecognized option: storage.journal.enabled
try '/opt/bitnami/mongodb/bin/mongod --help' for more information
```

**Comment by muyukha** [comment]
I got the issue.
I think the latest tag has a bug.
I updated the tag to `6.0.10-debian-11-r8` and evrything is running fine

**Comment by javsalgar** [comment]
Hi!

Did you set any custom values or configuration?

**Comment by muyukha** [comment]
Yes. I changed the image tag from `latest` to `6.0.10-debian-11-r8` in the helm values

**Comment by rafariossaa** [comment]
Hi,
  Could you indicate which chart version are  you using ?

**Comment by kidstell** [comment]
after reading this article below, i decided to comment out the journal part of my `mongod.conf`, now the start-up is fine. 
https://www.mongodb.com/docs/manual/reference/program/mongod/#options

The journal would always be enabled, perhaps I don't need to enable it myself. Nonetheless, I hope that if this is the case, an official response to confirm this can close this issue.

![image](https://github.com/bitnami/containers/assets/19243382/f00c096a-27d1-4398-9655-e60ca0b35c0d)

**Comment by JustDoItSascha** [comment]
I'm using the bitnami mongodb helm chart in version 15.6.22, which uses the mongodb image 7.0.14 and I have the exact same issue. Just out of the box install and it exits with exitCode 2 and after enable debug mode I see the same error...

**Comment by jfshark** [comment]
Dear bitnami,

Same issue, fixed in mongodb/7.0 by PR https://github.com/bitnami/containers/pull/65826 exists in the mongodb/8.0/debian-12 folder in the same file and line. All charts versions are not functional, cause this journaling issue prevents mongodb from start

**Comment by JustDoItSascha** [comment]
I'm so confused. It's still in issue in latest bitnami chart. Out of the box installation is still not possible. How can this not be a bigger problem?

**Comment by weeband** [comment]
weird things happen to me here, i deploy bitnami/mongodb to 2 cluster and got 2 behaviour, 
for the first one, it installed without issue, but on the second one, i get error after enable `image.debug`
```
Unrecognized option: storage.journal.enabled
try '/opt/bitnami/mongodb/bin/mongod --help' for more information
```

everything works after I remove `journal.enabled` from configuration
so previously, 
```
configuration: |-
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
...otherconfig
```
become
```

configuration: |-
  storage:
    dbPath: /bitnami/mongodb/data/db
...otherconfig
```

and it works.
i wonder why this behaviour isn't detected on my first cluster
