### ISSUE TITLE
[bitnami/moodle] Cannot connect to Postgresql with SSL/TLS connection when moodle database on RDS is setup with SSL/TLS.

### ISSUE THREAD

**Issue by sanlinnaing** [bitnami/containers#65832]
### Name and Version

bitnami/moodle:4.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

**1. Environment**
- docker hosted on Ubuntu 22.04
- docker compose
- Database : Postgresql hosted on AWS RDS with SSL/TLS=on
- REF setup : https://github.com/bitnami/containers/blob/main/bitnami/moodle/README.md

When setting up with docker compose by using `docker.io/bitnami/moodle:4.4` images, I have used Postgresql database hosted on AWS RDS.
AWS RDS config on for SSL/TLS.
I can connect postgresql databse from docker host using `psql` . There is no problem.
But when I run the docker compose and check logs of moodle and a request to exposed port, I found following error.
`pg_connect(): Unable to connect to PostgreSQL server: connection to server at ______failed: could not open certificate file &quot;/root/.postgresql/postgresql.crt&quot;: Permission denied`
![image](https://github.com/bitnami/containers/assets/10624135/cb8b14e7-ce78-4d3b-8442-c9cc4bea84f6)

It seem that apache user (`daemon` or `www-data`) have not right permission to `/root/.postgresql/postgresql.crt`.

### What is the expected behavior?

It should be able to connect to Postgresql just setting correct database endpoint on `MOODLE_DATABASE_HOST`.

### What do you see instead?

I found following error logs of moodle container when moodle initial setup from web.
![image](https://github.com/bitnami/containers/assets/10624135/e57c2638-12dd-41ef-91fe-4f592ef0d497)

### Additional information

**Workaround**
I found a way to overcome the `/root/.postgresql/postgresql.crt` access permission problem with following way.
Set environment variable `PGSSLCERT: /tmp/postgresql.crt` to overwrite the default postgresql.crt location.
reference : [postgresql docs](https://www.postgresql.org/docs/15/libpq-envars.html#:~:text=sslcompression%20connection%20parameter.-,PGSSLCERT,-behaves%20the%20same)
With this envrionment variable, there is no problem and I can successfully setup the moodle.

**Comment by gongomgra** [comment]
Hi @sanlinnaing,

Thanks for your message. Unfortunately, I don't fully understand if you need the SSL certificate to connect with the RDS database or not. Does the `/tmp/postgresql.crt` file exist on your container? According to the first screenshot, the message you received is just a warning. Did the Moodle app start correctly or did you need to configure the `PGSSLCERT` variable for it to start?

**Comment by raghumuppa** [comment]
No, we don't need an SSL certificate to connect to RDS and  /tmp/postgresql.crt doesn't exist in the container. To ignore the error, we need to configure the PGSSLCERT to point to any dummy location.

**Comment by sanlinnaing** [comment]
@raghumuppa 
Thanks for your comments. Your mention is correct.
@gongomgra 
We do not need a certificate to connect to RDS.
In case RDS config perfer SSL/TLS connection, in client side even though a certificate is not required to connect to RDS, it is required to configure `PGSSLCERT` with `/tmp/postgresql.crt` or any other accessible location.

**Comment by gongomgra** [comment]
HI @sanlinnaing, @raghumuppa,

Thanks for your messages. We are working on a new release including PGSSLCERT definition into `/tmp` folder. We will keep you posted.

**Comment by gongomgra** [comment]
Hi @sanlinnaing, @raghumuppa,

We have just released a new revision of our Moodle 4.4 image (tag `4.4.0-debian-12-r5`) including the changes mentioned in my previous message ([see pr/67709](https://github.com/bitnami/containers/pull/67709)). Can you confirm the Moodle app starts properly using that image and not defining the `PGSSLCERT` variable in your docker-compose?

**Comment by sanlinnaing** [comment]
@gongomgra 

Thanks for your information.
I have tested with `4.4.0-debian-12-r5` tag.
It seem that it does not solve.
Here is the part of the log:
```
moo-moodle-1  | [07-Jun-2024 14:02:14 UTC] PHP Warning:  pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;xxxx-xxxx-db.xxxxxxwspv.us-east-2.rds.amazonaws.com&quot; (10.2.169.196), port 5432 failed: could not open certificate file &quot;/root/.postgresql/postgresql.crt&quot;: Permission denied
moo-moodle-1  | connection to server at &quot;xxxx-xxxx-db.xxxxxxwspv.us-east-2.rds.amazonaws.com&quot; (10.2.169.196), port 5432 failed: FATAL:  no pg_hba.conf entry for host &quot;10.1.38.40&quot;, user &quot;moodleuser&quot;, database &quot;moodle&quot;, no encryption in /bitnami/moodle/lib/dml/pgsql_native_moodle_database.php on line 214
```
If I check the image version with `ps`, it is `docker.io/bitnami/moodle:4.4.0-debian-12-r5`.
```
ubuntu@ip-10-1-38-40:~/moo$ docker compose ps
NAME           IMAGE                                         COMMAND                                                                          SERVICE       CREATED         STATUS         PORTS
moo-moodle-1   docker.io/bitnami/moodle:4.4.0-debian-12-r5   "/opt/bitnami/scripts/moodle/entrypoint.sh /opt/bitnami/scripts/moodle/run.sh"   moodle        2 minutes ago   Up 2 minutes   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 8443/tcp
letsencrypt    jrcs/letsencrypt-nginx-proxy-companion        "/bin/bash /app/entrypoint.sh /bin/bash /app/start.sh"                           letsencrypt   2 minutes ago   Up 2 minutes   
nginx-proxy    jwilder/nginx-proxy:alpine                    "/app/docker-entrypoint.sh forego start -r"                                      nginx-proxy   2 minutes ago   Up 2 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp
```
Still same with `/root/.postgresql/postgresql.crt` instead of `/tmp/postgresql.crt`.

When I check the environment variables inside the container with `printenv` command, there is no `PGSSLCERT` variable found.

**Comment by gongomgra** [comment]
@sanlinnaing we have reverted the environment variables in PostgreSQL client until we have more information on this and we can think on a proper solution.

https://github.com/bitnami/containers/pull/68042
