### ISSUE TITLE
[bitnami/aws-cli] Bitbucket Pipelines fails silently unless `HOME` env is set to user-writeable directory

### ISSUE THREAD

**Issue by jarp0l** [bitnami/containers#81841]
### Name and Version

bitnami/aws-cli:*

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create a Bitbucket Pipeline with the following configuration:
```yml
image: bitnami/aws-cli
pipelines:
  default:
    - step:
        name: Test AWS CLI
        script:
          - export AWS_DEFAULT_REGION=us-east-1
          - export AWS_ROLE_ARN=arn:aws:iam::123456789012:role/oidc-role
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $AWS_WEB_IDENTITY_TOKEN_FILE
          - aws sts get-caller-identity
```
3. Commit and push the file and let the pipeline run.
4. Observe that the step appears to fail silently, no output is printed.

### What is the expected behavior?

The step should either:
- Succeed and print the output of `script` block and the expected output from `aws sts get-caller-identity` command, or
- Print an error message indicating why the step failed.

### What do you see instead?

- The step fails silently.
- No output or error message is printed, making it difficult to diagnose the issue.

### Additional information

- The root cause seems to be that the `HOME` environment variable is set to `/` in the image, which is not writable by the non-root user (uid=1001).

- When I override `HOME` in the pipeline step (e.g. `export HOME=/tmp` in the step's `script` block), the step succeeds, although still no output is shown:
```yml
        script:
          - export HOME=/tmp
          - ...
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $AWS_WEB_IDENTITY_TOKEN_FILE
          - aws sts get-caller-identity
```

- If I use my custom image in the pipeline based on `bitnami/aws-cli` where I set `HOME` to a writable directory in the Dockerfile (e.g. `/tmp`), both the pipeline/step execution and output work as expected.

- This issue seems to be related to another issue: https://github.com/bitnami/containers/issues/40781

#### Suggested fix
Update the Dockerfile to set the `HOME` environment variable to a user-writable directory, as done in another Bitnami image: https://github.com/bitnami/containers/blob/3202201d57eb4391ad4c69c46f32e32143d1c641/bitnami/dotnet/9/debian-12/Dockerfile#L20

| Without setting `HOME` env variable | After setting `HOME` env variable on my custom base image |
|----------------------|----------------------|
| ![Image](https://github.com/user-attachments/assets/216c1a5d-fb3f-4ec7-85dc-106047c6c29c) | ![Image](https://github.com/user-attachments/assets/7b0de79d-3101-458b-a89c-fdca5ae7467f) |

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by jarp0l** [comment]
I'd definitely love to contribute!

I have a question regarding the directory to use for the `HOME` env variable. Would using `/app` be fine as in the dotnet image? Or would you recommend creating a user-specific directory under `/home`, like `/home/aws-cli` or `/home/awscli`?

I've made the change (https://github.com/jarp0l/containers/commit/3b172c316a46f2c9545937af490423a720e1ca49) to use `HOME=/app`, and the image built from this Dockerfile is working as expected. But this means `/app` will be used as the `$HOME` directory, so tools like AWS CLI will store configuration files there.

**Comment by juan131** [comment]
Hi @jarp0l 

Thanks so much for reporting this issue!

I don't think we should modify the HOME env. var but ensuring the `/.aws` directory exists and there are write permissions for the non-root users on it. Taking [this Dockerfile](https://github.com/bitnami/containers/blob/main/bitnami/aws-cli/2/debian-12/Dockerfile) as a reference, it could be fixed by doing:

```diff
diff --git a/bitnami/aws-cli/2/debian-12/Dockerfile b/bitnami/aws-cli/2/debian-12/Dockerfile
index c996a8bd3e1..daa74786202 100644
--- a/bitnami/aws-cli/2/debian-12/Dockerfile
+++ b/bitnami/aws-cli/2/debian-12/Dockerfile
@@ -44,6 +44,7 @@ RUN apt-get update && apt-get upgrade -y && \
     apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
 RUN chmod g+rwX /opt/bitnami
 RUN find / -perm /6000 -type f -exec chmod a-s {} \; || true
+RUN mkdir -p /.aws && chmod g+rwX /.aws

 ENV APP_VERSION="2.27.20" \
     AWS_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt" \
```

What do you think?

**Comment by juan131** [comment]
This was addressed in the latest image revision (`2.27.30-debian-12-r1`), see [this commit](https://github.com/bitnami/containers/commit/629c95bfff856bff6614e5995761de62f32c0751).

**Comment by jarp0l** [comment]
Hi @juan131,
Apologies for not responding sooner. I did test the pipeline after this change, but it still failed. I wanted to investigate further to understand why, but I got caught up with other tasks.

Bitbucket Pipelines creates additional directories and files during execution, so I suspect it's failing because it can't create them in the `/` directory. This might also be related to the empty output on pipeline. Normally pipeline creates a `.bashrc` file in the `$HOME` directory with the following content:

```sh
exec >> /proc/1/fd/1 2>/proc/1/fd/2
```

But now since the user cannot write to `/` directory, it can't create the `.bashrc` file, which may be why nothing is being printed to stdout.

It looks like we need to do more than just change the permissions on `/.aws`. Neither this change nor simply setting `$HOME` to a different location seems ideal, as either could break others' workflows. I think the best option may be to create our own base image based on the Bitnami image and set the `$HOME` directory.
